# Header Menu
menu:
  Home: /
  Archives: /archives/
  Categories: /categories/
  Tags: /tags/
  MonthArchive: /month_archive/
  About: /about/
  # change github and email values to your own addresses
#  Github: 
#    url: https://github.com/justinchou
#    target: _blank
#  Gitee: 
#    url: https://gitee.com/justinchou
#    target: _blank
#  Email: mailto:zhou78620051@126.com
#  QQ: tencent://message/?uin=78620051&Site=qq&Menu=yes
rss: /atom.xml

since: 2012

# Set to false to disable banner
use_header_cover: true

# URL of the banner image
# Put your custom banner image under
# the theme's img folder: your-blog/themes/minimal-dual/source/img/
# and modify index_cover's value like so:
# index_cover: /img/your-custom-banner.jpg
# or
# Put your custom banner image under
# your blog's images folder: your-blog/source/images/
# and modify index_cover's value like so:
# index_cover: /images/your-custom-banner.jpg
# or
# Specify an online resource like so:
# index_cover: http://somewhere.com/path/to/banner.jpg
index_cover: /img/default-banner-dark.jpg
# index_cover: /img/default-banner-light.jpg

widgets:
- category
- archive
- tag
- tagcloud
- month_archive
- recent_posts

# theme_style is default to 'light', change to dark?
# theme_style: dark

# widget behavior
archive_type: 'monthly'
show_count: false

# Changyan Comments
changyan:
  appid: 
  config: 
# Disqus Comments
disqus_shortname:

# Analysis
## Baidu Analysis Tracking ID
baidu_analytics: 
## Google Analysis Tracking ID
google_analytics:



# favicon
favicon: /favicon.png


